export const youLostSentences = [
  "Your memory needs a super effective move!",
  "A wild forgetfulness appeared. You fainted!",
  "Your memory needs a Potion.",
  "Your memory was hit by a critical hit amnesia!",
  "It's super effective! Your memory faded.",
  "Your memory fainted! It needs a Revive.",
  "Your memory played hide and seek and got lost forever.",
  "Your memory is lost in the tall grass. Can't find it!",
  "Oh no, your memory fainted in the heat of battle!",
  "Your memory went on a journey but forgot to come back.",
  "Your memory got tangled in the vines of confusion.",
  "Your memory took a wrong turn at the crossroads.",
  "A memory fog rolled in, obscuring your thoughts.",
  "Your memory is playing hide and seek. It's hiding well!",
  "Your memory encountered a mental blackout.",
  "A wild amnesia storm swept away your memories.",
  "Your memory experienced a mental freeze.",
  "Your memory encountered a mental roadblock.",
  "Your memory is adrift in the sea of forgetfulness.",
  "A memory void devoured your recollections.",
];
